### PR TITLE
Update all dependencies

### PR DESCRIPTION
**Pull request by rejas**

### CODE REVIEW

**Comment by sjentzsch** [comment]
Would love to see dependency version being upgraded. Does anyone has an idea why the build fail? The job logs (to me at least) do not tell much.

**Comment by rejas** [comment]
Narrowed the build error down to the coffeescript dependency. I am not to familiar with it to fix that.
The rest of the updated dependencies at least removes all warnings from npm audit fix.

**Comment by rejas** [comment]
Thx for merging @AveVlad Any estimation when you will release a new version to npm?

**Comment by AveVlad** [comment]
@rejas `gulp-connect@5.6.1`

> gulp-connect@5.6.1 prepublish .
> coffee -o . -bc src/

npm notice
npm notice 📦  gulp-connect@5.6.1
npm notice === Tarball Contents ===
npm notice 1.4kB   package.json
npm notice 72B     .travis.yml
npm notice 8.7kB   index.js
npm notice 167.8kB jetbrains.png
npm notice 1.1kB   LICENSE
npm notice 4.6kB   README.md
npm notice 768B    bin/make_certs.sh
npm notice 1.1kB   certs/server.crt
npm notice 1.7kB   certs/server.key
npm notice 6.2kB   src/index.coffee
npm notice 8B      test/fixtures/multiple/app/index.html
npm notice 9B      test/fixtures/multiple/dist/dist.html
npm notice 11B     test/fixtures/simplest/index.html
npm notice 11B     test/fixtures/simplest/test.txt
npm notice 6.0kB   test/test.js
npm notice === Tarball Details ===
npm notice name:          gulp-connect
npm notice version:       5.6.1
npm notice package size:  162.1 kB
npm notice unpacked size: 199.4 kB

+ gulp-connect@5.6.1

**Comment by AveVlad** [comment]
@rejas Thanks!

**Pull request merged**
