### PR TITLE
Add a config option for preferring HTTP1

### PR DESCRIPTION
**Pull request by nickpape-msft**
See https://github.com/AveVlad/gulp-connect/issues/246

### CODE REVIEW

**Comment by nickpape-msft** [comment]
@AveVlad, do you mind looking at this? It is causing problems with `gulp-connect` and Node 8.

**Comment by nickpape-msft** [comment]
Ping @zbennett10  @AveVlad

**Comment by AveVlad** [comment]
@nickpape-msft Thanks!

`gulp-connect@5.4.0`

**Comment by nickpape-msft** [comment]
Thanks a bunch!

**Pull request merged**
