### PR TITLE
Add server plugins (to use with socket.io and such)

### PR DESCRIPTION
**Pull request by rusintez**

### CODE REVIEW

**Comment by Foxandxss** [comment]
Well seems like this repo is kinda dead. @AveVlad are you going to merge stuff like this? It is really needed :)

**Comment by justinmchase** [comment]
Can you update this PR? I will test it out and merge it.

**Comment by justinmchase** [comment]
This should be fixed by #160 

Though it will be slightly different, it would look more like this:

```
gulp.task('connect', function() {
  var app = connect.server();
  var io = socketio(app.server);
  io.on('connection', function(socket) {
    // do stuff
  });
});
```

**Comment by achingbrain** [comment]
@justinmchase Nice work - any chance of a new release?

**Comment by justinmchase** [comment]
Soon hopefully. I want to test the live-reload stuff a little more. Its a little trickier, since you can only have 1 at a time I think.

**Comment by ybonnefond** [comment]
@justinmchase Did you have time to do the tests? Do you know roughly when this is going to be released?

**Comment by justinmchase** [comment]
Released in https://github.com/AveVlad/gulp-connect/releases/tag/v3.0.0

I made a major version release in case there are breaking changes. You should be able to do the middleware configuration using the code snippet I included above now. Let me know if you have any issues!

**Comment by ybonnefond** [comment]
Great! thanks @justinmchase

**Pull request closed without merging**
